# Generated by Django 4.2.2 on 2023-06-05 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('type', models.CharField(default='event', max_length=10)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('schedule', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.IntegerField(choices=[(1, 'event_1'), (2, 'event_2')])),
                ('sub_category', models.IntegerField(choices=[(1, 'sub_event_1'), (2, 'sub_event_2')])),
                ('rigor_rank', models.IntegerField(default=0)),
                ('attendees', models.ManyToManyField(related_name='attendees_event', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
